site_name: tplink-smartdevices-docs
nav:
    - Home: 'index.md'
    - 'Getting Started': 'getting-started.md'
    - Timer: 'timer.md'
    - Schedule: 'schedule.md'
    - Docs:
      - 'TPLinkDiscovery': 'docs/discovery.md'
      - Devices: 
        - 'TPLinkSmartDevice': 'docs/devices/device.md'
        - 'TPLinkSmartPlug': 'docs/devices/plug.md'
        - 'TPLinkSmartMeterPlug': 'docs/devices/smartmeter-plug.md'
        - 'TPLinkSmartBulb': 'docs/devices/bulb.md'
        - 'TPLinkSmartMultiPlug': 'docs/devices/multi-plug.md'
        - 'TPLinkSmartDimmer': 'docs/devices/dimmer.md'
      - Data:
        - 'BulbHSV': 'docs/data/hsv.md'
        - 'PowerData': 'docs/data/power.md'
        - 'LightDetails': 'docs/data/light-details.md'
theme:
  name: material
  favicon: assets/icon.png
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CodeBardian
repo_url: https://www.github.com/CodeBardian/tplink-smartdevices-netstandard
repo_name: CodeBardian/tplink-smartdevices-netstandard
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
google_analytics:
  - UA-145854471-2
  - auto